id: IFB283BBB
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-11T13:21:34.515118'
last_modified: '2022-06-11T13:21:34.515127'
parser: null
source_metadata:
  title: Yukhok Chöying Rangdrol Series
  language: en
  description: 'Texts by Yukhok Chatralwa Chöying Rangdrol (g.yu khog bya bral ba
    chos dbyings rang grol, 1872–1952), including extracts from his Ngöndro Compendium,
    a commentary on the Longchen Nyingtik preliminary practices:'
  volume:
    f65BD:
      title: Advice to Damngak Gyatso of Do
      base_file: f65BD.txt
      order: 1
      parent: Advice
    f0A18:
      title: From the Oral Tradition of the Lama of Nyarong
      base_file: f0A18.txt
      order: 2
      parent: Advice
    fCE85:
      title: Brief Explanation of Clarification and Transcendental Resolution from
        the Oral Tradition of Nyala Sogyal
      base_file: fCE85.txt
      order: 3
      parent: Dzogchen
    fFAFD:
      title: Commentary on Vajra Verses on the Natural State
      base_file: fFAFD.txt
      order: 4
      parent: Dzogchen
    fAB9F:
      title: How Liberation and Delusion Develop Out of the Clear Light of the Ground,
        etc.
      base_file: fAB9F.txt
      order: 5
      parent: Dzogchen
    fDF45:
      title: Notes from the Oral Tradition on Ālaya, Ālaya Consciousness, etc.
      base_file: fDF45.txt
      order: 6
      parent: Dzogchen
    fD59B:
      title: Ngöndro Compendium—Part 1—Invoking the Lama
      base_file: fD59B.txt
      order: 7
      parent: Ngöndro Compendium
    f8A9A:
      title: Ngöndro Compendium—Part 2—Taking Refuge
      base_file: f8A9A.txt
      order: 8
      parent: Ngöndro Compendium
    f1A2B:
      title: Ngöndro Compendium—Part 3—Arousing Bodhichitta
      base_file: f1A2B.txt
      order: 9
      parent: Ngöndro Compendium
    f24B4:
      title: Ngöndro Compendium—Part 4—Mandala Offering
      base_file: f24B4.txt
      order: 10
      parent: Ngöndro Compendium
    fEAEE:
      title: The Final Testament of Yukhok Chatralwa as Transmitted to Lama Rigdzin
        Nyima
      base_file: fEAEE.txt
      order: 11
      parent: Testament
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
